/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apotekv2;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Form_Laporan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form_Laporan.class.getName());

    /**
     * Creates new form Form_Laporan
     */
    public Form_Laporan() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Btn_LapStok = new javax.swing.JButton();
        Btn_LapJual = new javax.swing.JButton();
        Btn_LapBeli = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Laporan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("LAPORAN APOTEK");

        Btn_LapStok.setText("Laporan Stok Menipis");
        Btn_LapStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LapStokActionPerformed(evt);
            }
        });

        Btn_LapJual.setText("Laporan Penjualan");
        Btn_LapJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LapJualActionPerformed(evt);
            }
        });

        Btn_LapBeli.setText("Laporan Restock");
        Btn_LapBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LapBeliActionPerformed(evt);
            }
        });

        Tbl_Laporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tbl_Laporan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_LapBeli)
                    .addComponent(Btn_LapJual)
                    .addComponent(Btn_LapStok)
                    .addComponent(jLabel1))
                .addContainerGap(497, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(Btn_LapStok)
                .addGap(18, 18, 18)
                .addComponent(Btn_LapJual)
                .addGap(18, 18, 18)
                .addComponent(Btn_LapBeli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_LapStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LapStokActionPerformed
        try {
            Connection conn = KoneksiDb.getKoneksi();
            Statement st = conn.createStatement();
            // Tampilkan obat yang stoknya 10 atau kurang
            ResultSet rs = st.executeQuery("SELECT * FROM obat WHERE stok <= 10 ORDER BY stok ASC");
            
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID Obat");
            model.addColumn("Nama Obat");
            model.addColumn("Kategori");
            model.addColumn("Sisa Stok");
            
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_obat"),
                    rs.getString("nama_obat"),
                    rs.getString("kategori"),
                    rs.getInt("stok")
                });
            }
            Tbl_Laporan.setModel(model);
            
            if (model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Aman! Tidak ada stok obat yang menipis.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_Btn_LapStokActionPerformed

    private void Btn_LapJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LapJualActionPerformed
        try {
            Connection conn = KoneksiDb.getKoneksi();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT id_jual, tanggal, username, sumber, total FROM transaksi_jual ORDER BY tanggal DESC");
            
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID Transaksi");
            model.addColumn("Tanggal");
            model.addColumn("Pembeli");
            model.addColumn("Sumber Transaksi");
            model.addColumn("Total Pemasukan");
            
            int totalPemasukan = 0; // Untuk hitung total semua
            
            while (rs.next()) {
                int total = rs.getInt("total");
                totalPemasukan += total;
                
                model.addRow(new Object[]{
                    rs.getString("id_jual"),
                    rs.getString("tanggal"),
                    rs.getString("username"),
                    rs.getString("sumber"),
                    "Rp " + total
                });
            }
            Tbl_Laporan.setModel(model);
            
            JOptionPane.showMessageDialog(null, "Total Seluruh Pemasukan: Rp " + totalPemasukan);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_Btn_LapJualActionPerformed

    private void Btn_LapBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LapBeliActionPerformed
        try {
            Connection conn = KoneksiDb.getKoneksi();
            Statement st = conn.createStatement();
            String sql = "SELECT t.id_beli, t.tanggal, s.nama_supplier, t.total " +
                         "FROM transaksi_beli t JOIN supplier s ON t.id_supplier = s.id_supplier " +
                         "ORDER BY t.tanggal DESC";
            ResultSet rs = st.executeQuery(sql);
            
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID Restock");
            model.addColumn("Tanggal");
            model.addColumn("Nama Supplier");
            model.addColumn("Total Pengeluaran");
            
            int totalPengeluaran = 0;
            
            while (rs.next()) {
                int total = rs.getInt("total");
                totalPengeluaran += total;
                
                model.addRow(new Object[]{
                    rs.getString("id_beli"),
                    rs.getString("tanggal"),
                    rs.getString("nama_supplier"),
                    "Rp " + total
                });
            }
            Tbl_Laporan.setModel(model);
            
            JOptionPane.showMessageDialog(null, "Total Seluruh Pengeluaran (Beli Obat): Rp " + totalPengeluaran);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_Btn_LapBeliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Form_Laporan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_LapBeli;
    private javax.swing.JButton Btn_LapJual;
    private javax.swing.JButton Btn_LapStok;
    private javax.swing.JTable Tbl_Laporan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
