/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apotekv2;

/**
 *
 * @author Bagas
 */
public class Form_MenuAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form_MenuAdmin.class.getName());

    /**
     * Creates new form Form_MenuAdmin
     */
    public Form_MenuAdmin() {
        initComponents();
        Lbl_Welcome.setText("Selamat Datang, Admin " + UserSession.getNamaLengkap());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Lbl_Welcome = new javax.swing.JLabel();
        Btn_Obat = new javax.swing.JButton();
        Btn_Supplier = new javax.swing.JButton();
        Btn_Restock = new javax.swing.JButton();
        Btn_Kasir = new javax.swing.JButton();
        Btn_Laporan = new javax.swing.JButton();
        Btn_Logout = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Btn_Obat.setText("Kelola Data Obat");
        Btn_Obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ObatActionPerformed(evt);
            }
        });

        Btn_Supplier.setText("Kelola Data Supplier");
        Btn_Supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SupplierActionPerformed(evt);
            }
        });

        Btn_Restock.setText("Restock / Beli Obat");
        Btn_Restock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_RestockActionPerformed(evt);
            }
        });

        Btn_Kasir.setText("Kasir Penjualan");
        Btn_Kasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_KasirActionPerformed(evt);
            }
        });

        Btn_Laporan.setText("Laporan Apotek");
        Btn_Laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LaporanActionPerformed(evt);
            }
        });

        Btn_Logout.setText("Logout");
        Btn_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Lbl_Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Btn_Supplier)
                        .addComponent(Btn_Obat)
                        .addComponent(Btn_Restock)
                        .addComponent(Btn_Kasir)
                        .addComponent(Btn_Laporan)
                        .addComponent(Btn_Logout)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Lbl_Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Obat)
                .addGap(18, 18, 18)
                .addComponent(Btn_Supplier)
                .addGap(18, 18, 18)
                .addComponent(Btn_Restock)
                .addGap(18, 18, 18)
                .addComponent(Btn_Kasir)
                .addGap(18, 18, 18)
                .addComponent(Btn_Laporan)
                .addGap(18, 18, 18)
                .addComponent(Btn_Logout)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_ObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ObatActionPerformed
        new Form_Obat().setVisible(true);
    // this.dispose(); -> JANGAN pakai ini, biarkan menu tetap terbuka di background
    }//GEN-LAST:event_Btn_ObatActionPerformed

    private void Btn_SupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SupplierActionPerformed
        new Form_Supplier().setVisible(true);
    }//GEN-LAST:event_Btn_SupplierActionPerformed

    private void Btn_RestockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_RestockActionPerformed
       new Form_Restock().setVisible(true);
    }//GEN-LAST:event_Btn_RestockActionPerformed

    private void Btn_KasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_KasirActionPerformed
        new Form_Kasir().setVisible(true);
    }//GEN-LAST:event_Btn_KasirActionPerformed

    private void Btn_LaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LaporanActionPerformed
        new Form_Laporan().setVisible(true);
    }//GEN-LAST:event_Btn_LaporanActionPerformed

    private void Btn_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LogoutActionPerformed
        UserSession.logout(); // Hapus memori sesi
    new Form_Login().setVisible(true); // Kembali ke login
    this.dispose(); // Tutup menu admin
    }//GEN-LAST:event_Btn_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Form_MenuAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Kasir;
    private javax.swing.JButton Btn_Laporan;
    private javax.swing.JButton Btn_Logout;
    private javax.swing.JButton Btn_Obat;
    private javax.swing.JButton Btn_Restock;
    private javax.swing.JButton Btn_Supplier;
    private javax.swing.JLabel Lbl_Welcome;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
