/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apotekv2;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Form_Obat extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form_Obat.class.getName());

    /**
     * Creates new form Form_Obat
     */
    public Form_Obat() {
        initComponents();
        loadData();
        // Agar kalau di-close (X), kembali ke Menu Admin, bukan matiin aplikasi
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    
     private void loadData() {
        try {
            Connection conn = KoneksiDb.getKoneksi();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM obat");
            
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID Obat");
            model.addColumn("Nama Obat");
            model.addColumn("Kategori");
            model.addColumn("Harga Beli");
            model.addColumn("Harga Jual");
            model.addColumn("Stok");
            
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_obat"),
                    rs.getString("nama_obat"),
                    rs.getString("kategori"),
                    rs.getInt("harga_beli"),
                    rs.getInt("harga_jual"),
                    rs.getInt("stok")
                });
            }
            Tbl_Obat.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error load data: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Cb_Kategori = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Ed_IdObat = new javax.swing.JTextField();
        Ed_HargaBeli = new javax.swing.JTextField();
        Ed_HargaJual = new javax.swing.JTextField();
        Ed_Stok = new javax.swing.JTextField();
        Btn_Simpan = new javax.swing.JButton();
        Btn_Update = new javax.swing.JButton();
        Btn_Hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Obat = new javax.swing.JTable();
        Ed_NamaObat = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Obat");

        jLabel2.setText("Nama Obat");

        jLabel3.setText("Kategori");

        Cb_Kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tablet", "Kapsul", "Sirup", "Salep" }));

        jLabel4.setText("Harga Beli");

        jLabel5.setText("Harga Jual");

        jLabel6.setText("Stok Awal");

        Btn_Simpan.setText("Simpan");
        Btn_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SimpanActionPerformed(evt);
            }
        });

        Btn_Update.setText("Update");
        Btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_UpdateActionPerformed(evt);
            }
        });

        Btn_Hapus.setText("Hapus");
        Btn_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_HapusActionPerformed(evt);
            }
        });

        Tbl_Obat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tbl_Obat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tbl_ObatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbl_Obat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(13, 13, 13))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(22, 22, 22))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addGap(12, 12, 12)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(Ed_IdObat, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Cb_Kategori, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ed_HargaBeli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ed_HargaJual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ed_Stok, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ed_NamaObat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Btn_Update)
                            .addComponent(Btn_Simpan)
                            .addComponent(Btn_Hapus))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Ed_IdObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Ed_NamaObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Cb_Kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Ed_HargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Ed_HargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Ed_Stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Btn_Simpan)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_Update)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_Hapus)))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SimpanActionPerformed
        try {
            Connection conn = KoneksiDb.getKoneksi();
            String sql = "INSERT INTO obat VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, Ed_IdObat.getText());
            pst.setString(2, Ed_NamaObat.getText());
            pst.setString(3, Cb_Kategori.getSelectedItem().toString());
            pst.setInt(4, Integer.parseInt(Ed_HargaBeli.getText()));
            pst.setInt(5, Integer.parseInt(Ed_HargaJual.getText()));
            pst.setInt(6, Integer.parseInt(Ed_Stok.getText()));
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Obat Berhasil Disimpan!");
            loadData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Simpan: " + e.getMessage());
        }
    }//GEN-LAST:event_Btn_SimpanActionPerformed

    private void Tbl_ObatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl_ObatMouseClicked
        int row = Tbl_Obat.getSelectedRow();
        if (row != -1) {
            Ed_IdObat.setText(Tbl_Obat.getValueAt(row, 0).toString());
            Ed_NamaObat.setText(Tbl_Obat.getValueAt(row, 1).toString());
            Cb_Kategori.setSelectedItem(Tbl_Obat.getValueAt(row, 2).toString());
            Ed_HargaBeli.setText(Tbl_Obat.getValueAt(row, 3).toString());
            Ed_HargaJual.setText(Tbl_Obat.getValueAt(row, 4).toString());
            Ed_Stok.setText(Tbl_Obat.getValueAt(row, 5).toString());
            Ed_IdObat.setEditable(false); 
        }
    }//GEN-LAST:event_Tbl_ObatMouseClicked

    private void Btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_UpdateActionPerformed
        try {
            Connection conn = KoneksiDb.getKoneksi();
            String sql = "UPDATE obat SET nama_obat=?, kategori=?, harga_beli=?, harga_jual=?, stok=? WHERE id_obat=?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, Ed_NamaObat.getText());
            pst.setString(2, Cb_Kategori.getSelectedItem().toString());
            pst.setInt(3, Integer.parseInt(Ed_HargaBeli.getText()));
            pst.setInt(4, Integer.parseInt(Ed_HargaJual.getText()));
            pst.setInt(5, Integer.parseInt(Ed_Stok.getText()));
            pst.setString(6, Ed_IdObat.getText());
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Data Obat Diupdate!");
            Ed_IdObat.setEditable(true);
            loadData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Update: " + e.getMessage());
        }
    }//GEN-LAST:event_Btn_UpdateActionPerformed

    private void Btn_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_HapusActionPerformed
        try {
            Connection conn = KoneksiDb.getKoneksi();
            String sql = "DELETE FROM obat WHERE id_obat=?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, Ed_IdObat.getText());
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Obat Dihapus!");
            Ed_IdObat.setEditable(true);
            loadData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Hapus: " + e.getMessage());
        }
    }//GEN-LAST:event_Btn_HapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Form_Obat().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Hapus;
    private javax.swing.JButton Btn_Simpan;
    private javax.swing.JButton Btn_Update;
    private javax.swing.JComboBox<String> Cb_Kategori;
    private javax.swing.JTextField Ed_HargaBeli;
    private javax.swing.JTextField Ed_HargaJual;
    private javax.swing.JTextField Ed_IdObat;
    private javax.swing.JTextField Ed_NamaObat;
    private javax.swing.JTextField Ed_Stok;
    private javax.swing.JTable Tbl_Obat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
