/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apotekv2;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Form_Restock extends javax.swing.JFrame {
    private DefaultTableModel tabMode;
    private int totalBelanja = 0;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form_Restock.class.getName());

    /**
     * Creates new form Form_Restock
     */
    public Form_Restock() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        // Setup Tabel Keranjang
        tabMode = new DefaultTableModel();
        tabMode.addColumn("ID Obat");
        tabMode.addColumn("Nama Obat");
        tabMode.addColumn("Harga Beli");
        tabMode.addColumn("Jumlah");
        tabMode.addColumn("Subtotal");
        Tbl_Keranjang.setModel(tabMode);
        
        loadComboBoxes();
    }

    private void loadComboBoxes() {
        try {
            Connection conn = KoneksiDb.getKoneksi();
            Statement st = conn.createStatement();
            
            // Load Supplier
            ResultSet rsSupp = st.executeQuery("SELECT id_supplier, nama_supplier FROM supplier");
            Cb_Supplier.removeAllItems();
            while (rsSupp.next()) {
                Cb_Supplier.addItem(rsSupp.getString("id_supplier") + " - " + rsSupp.getString("nama_supplier"));
            }
            
            // Load Obat
            ResultSet rsObat = st.executeQuery("SELECT id_obat, nama_obat FROM obat");
            Cb_Obat.removeAllItems();
            while (rsObat.next()) {
                Cb_Obat.addItem(rsObat.getString("id_obat") + " - " + rsObat.getString("nama_obat"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error load combobox: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Ed_IdRestock = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Cb_Supplier = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Cb_Obat = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Ed_Jumlah = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Ed_Subtotal = new javax.swing.JTextField();
        Btn_Tambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Keranjang = new javax.swing.JTable();
        Lbl_Total = new javax.swing.JLabel();
        Btn_Simpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Restock");

        jLabel2.setText("Pilih Supplier");

        Cb_Supplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Pilih Obat");

        Cb_Obat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Jumlah Beli");

        Ed_Jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Ed_JumlahKeyReleased(evt);
            }
        });

        jLabel5.setText("Subtotal");

        Btn_Tambah.setText("Tambah");
        Btn_Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_TambahActionPerformed(evt);
            }
        });

        Tbl_Keranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tbl_Keranjang);

        Lbl_Total.setText("Total: Rp 0");

        Btn_Simpan.setText("Simpan Transaksi Restock");
        Btn_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Simpan)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Ed_IdRestock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Cb_Supplier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Ed_Subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Cb_Obat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Ed_Jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(Btn_Tambah))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(Lbl_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Ed_IdRestock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Cb_Supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Cb_Obat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Ed_Jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Ed_Subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Btn_Tambah)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Lbl_Total)
                .addGap(18, 18, 18)
                .addComponent(Btn_Simpan)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ed_JumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ed_JumlahKeyReleased
        try {
            if (Ed_Jumlah.getText().isEmpty() || Cb_Obat.getSelectedItem() == null) {
                Ed_Subtotal.setText("0");
                return;
            }
            String idObat = Cb_Obat.getSelectedItem().toString().split(" - ")[0];
            int jumlah = Integer.parseInt(Ed_Jumlah.getText());
            
            Connection conn = KoneksiDb.getKoneksi();
            PreparedStatement pst = conn.prepareStatement("SELECT harga_beli FROM obat WHERE id_obat=?");
            pst.setString(1, idObat);
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                int hargaBeli = rs.getInt("harga_beli");
                Ed_Subtotal.setText(String.valueOf(hargaBeli * jumlah));
            }
        } catch (Exception e) {
            Ed_Subtotal.setText("0");
        }
    }//GEN-LAST:event_Ed_JumlahKeyReleased

    private void Btn_TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_TambahActionPerformed
        try {
            String selectedObat = Cb_Obat.getSelectedItem().toString();
            String idObat = selectedObat.split(" - ")[0];
            String namaObat = selectedObat.split(" - ")[1];
            
            int jumlah = Integer.parseInt(Ed_Jumlah.getText());
            int subtotal = Integer.parseInt(Ed_Subtotal.getText());
            int hargaBeli = subtotal / jumlah;
            
            // Masukkan ke tabel di layar
            tabMode.addRow(new Object[]{idObat, namaObat, hargaBeli, jumlah, subtotal});
            
            // Hitung total
            totalBelanja += subtotal;
            Lbl_Total.setText("Total: Rp " + totalBelanja);
            
            // Bersihkan input
            Ed_Jumlah.setText("");
            Ed_Subtotal.setText("0");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Pilih obat dan isi jumlah dengan benar!");
        }
    }//GEN-LAST:event_Btn_TambahActionPerformed

    private void Btn_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SimpanActionPerformed
        try {
            if (tabMode.getRowCount() == 0 || Ed_IdRestock.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "ID Transaksi kosong atau keranjang masih kosong!");
                return;
            }
            
            Connection conn = KoneksiDb.getKoneksi();
            
            String idRestock = Ed_IdRestock.getText();
            String idSupplier = Cb_Supplier.getSelectedItem().toString().split(" - ")[0];
            String tanggal = new SimpleDateFormat("yyyy-MM-dd").format(new Date()); // Otomatis hari ini!
            
            // 1. Simpan ke transaksi_beli
            String sqlBeli = "INSERT INTO transaksi_beli VALUES (?, ?, ?, ?)";
            PreparedStatement pstBeli = conn.prepareStatement(sqlBeli);
            pstBeli.setString(1, idRestock);
            pstBeli.setString(2, tanggal);
            pstBeli.setString(3, idSupplier);
            pstBeli.setInt(4, totalBelanja);
            pstBeli.execute();
            
            // 2. Simpan ke detail_beli dan TAMBAH STOK
            for (int i = 0; i < tabMode.getRowCount(); i++) {
                String idDetail = idRestock + "-" + i;
                String idObat = Tbl_Keranjang.getValueAt(i, 0).toString();
                int jumlah = Integer.parseInt(Tbl_Keranjang.getValueAt(i, 3).toString());
                int subtotal = Integer.parseInt(Tbl_Keranjang.getValueAt(i, 4).toString());
                
                // Insert detail
                String sqlDetail = "INSERT INTO detail_beli VALUES (?, ?, ?, ?, ?)";
                PreparedStatement pstDetail = conn.prepareStatement(sqlDetail);
                pstDetail.setString(1, idDetail);
                pstDetail.setString(2, idRestock);
                pstDetail.setString(3, idObat);
                pstDetail.setInt(4, jumlah);
                pstDetail.setInt(5, subtotal);
                pstDetail.execute();
                
                // Update Stok Obat (+)
                String sqlStok = "UPDATE obat SET stok = stok + ? WHERE id_obat=?";
                PreparedStatement pstStok = conn.prepareStatement(sqlStok);
                pstStok.setInt(1, jumlah);
                pstStok.setString(2, idObat);
                pstStok.execute();
            }
            
            JOptionPane.showMessageDialog(null, "Restock Berhasil! Stok Obat sudah bertambah.");
            
            // Reset form
            Ed_IdRestock.setText("");
            tabMode.setRowCount(0);
            totalBelanja = 0;
            Lbl_Total.setText("Total: Rp 0");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Simpan Transaksi: " + e.getMessage());
        }
    }//GEN-LAST:event_Btn_SimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Form_Restock().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Simpan;
    private javax.swing.JButton Btn_Tambah;
    private javax.swing.JComboBox<String> Cb_Obat;
    private javax.swing.JComboBox<String> Cb_Supplier;
    private javax.swing.JTextField Ed_IdRestock;
    private javax.swing.JTextField Ed_Jumlah;
    private javax.swing.JTextField Ed_Subtotal;
    private javax.swing.JLabel Lbl_Total;
    private javax.swing.JTable Tbl_Keranjang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
