/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apotekv2;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Form_TokoPelanggan extends javax.swing.JFrame {
    private DefaultTableModel tabMode;
    private int totalBelanja = 0;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form_TokoPelanggan.class.getName());

    /**
     * Creates new form Form_TokoPelanggan
     */
    public Form_TokoPelanggan() {
        initComponents();
     Lbl_Welcome.setText("Halo, " + UserSession.getNamaLengkap() + "! Selamat Berbelanja.");
        
        tabMode = new DefaultTableModel();
        tabMode.addColumn("ID Obat");
        tabMode.addColumn("Nama Obat");
        tabMode.addColumn("Harga");
        tabMode.addColumn("Jumlah");
        tabMode.addColumn("Subtotal");
        Tbl_Keranjang.setModel(tabMode);
        
        loadObat();
    }

    private void loadObat() {
        try {
            Connection conn = KoneksiDb.getKoneksi();
            Statement st = conn.createStatement();
            // Hanya tampilkan obat yang stoknya masih ada
            ResultSet rs = st.executeQuery("SELECT id_obat, nama_obat FROM obat WHERE stok > 0");
            Cb_Obat.removeAllItems();
            while (rs.next()) {
                Cb_Obat.addItem(rs.getString("id_obat") + " - " + rs.getString("nama_obat"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error load obat: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl_Welcome = new javax.swing.JLabel();
        Btn_Logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Cb_Obat = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Ed_Jumlah = new javax.swing.JTextField();
        Ed_Subtotal = new javax.swing.JTextField();
        Btn_Tambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Keranjang = new javax.swing.JTable();
        Lbl_Total = new javax.swing.JLabel();
        Btn_Bayar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Btn_Logout.setText("Logout");
        Btn_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LogoutActionPerformed(evt);
            }
        });

        jLabel2.setText("Pilih Obat");

        Cb_Obat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Jumlah Beli");

        jLabel4.setText("Subtotal");

        Ed_Subtotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Ed_SubtotalKeyReleased(evt);
            }
        });

        Btn_Tambah.setText("Masukkan Keranjang");
        Btn_Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_TambahActionPerformed(evt);
            }
        });

        Tbl_Keranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tbl_Keranjang);

        Lbl_Total.setText("Total Belanja: Rp 0");

        Btn_Bayar.setText("Checkout & Bayar");
        Btn_Bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BayarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Btn_Logout))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(Btn_Tambah))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Bayar)
                            .addComponent(Lbl_Total)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Cb_Obat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Ed_Jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Ed_Subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(Lbl_Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lbl_Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_Logout)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Cb_Obat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Ed_Jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Ed_Subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Btn_Tambah)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lbl_Total)
                .addGap(18, 18, 18)
                .addComponent(Btn_Bayar)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ed_SubtotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ed_SubtotalKeyReleased
        try {
            if (Ed_Jumlah.getText().isEmpty() || Cb_Obat.getSelectedItem() == null) {
                Ed_Subtotal.setText("0");
                return;
            }
            String idObat = Cb_Obat.getSelectedItem().toString().split(" - ")[0];
            int jumlah = Integer.parseInt(Ed_Jumlah.getText());
            
            Connection conn = KoneksiDb.getKoneksi();
            PreparedStatement pst = conn.prepareStatement("SELECT harga_jual FROM obat WHERE id_obat=?");
            pst.setString(1, idObat);
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                int hargaJual = rs.getInt("harga_jual");
                Ed_Subtotal.setText(String.valueOf(hargaJual * jumlah));
            }
        } catch (Exception e) {
            Ed_Subtotal.setText("0");
        }
    }//GEN-LAST:event_Ed_SubtotalKeyReleased

    private void Btn_TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_TambahActionPerformed
        try {
            String selectedObat = Cb_Obat.getSelectedItem().toString();
            String idObat = selectedObat.split(" - ")[0];
            String namaObat = selectedObat.split(" - ")[1];
            
            int jumlah = Integer.parseInt(Ed_Jumlah.getText());
            int subtotal = Integer.parseInt(Ed_Subtotal.getText());
            int harga = subtotal / jumlah;
            
            tabMode.addRow(new Object[]{idObat, namaObat, harga, jumlah, subtotal});
            
            totalBelanja += subtotal;
            Lbl_Total.setText("Total Belanja: Rp " + totalBelanja);
            
            Ed_Jumlah.setText("");
            Ed_Subtotal.setText("0");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Isi jumlah dengan benar!");
        }
    }//GEN-LAST:event_Btn_TambahActionPerformed

    private void Btn_BayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BayarActionPerformed
        try {
            if (tabMode.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Keranjang belanja masih kosong!");
                return;
            }
            
            Connection conn = KoneksiDb.getKoneksi();
            // Buat ID Transaksi acak untuk pelanggan
            String idTransaksi = "TRX" + (System.currentTimeMillis() % 10000); 
            String pembeli = UserSession.getUsername(); // Ambil username yang sedang login
            String tanggal = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
            
            // 1. Simpan ke transaksi_jual
            String sqlJual = "INSERT INTO transaksi_jual VALUES (?, ?, ?, 'Pelanggan Mandiri', ?)";
            PreparedStatement pstJual = conn.prepareStatement(sqlJual);
            pstJual.setString(1, idTransaksi);
            pstJual.setString(2, tanggal);
            pstJual.setString(3, pembeli);
            pstJual.setInt(4, totalBelanja);
            pstJual.execute();
            
            // 2. Simpan ke detail_jual dan KURANGI STOK
            for (int i = 0; i < tabMode.getRowCount(); i++) {
                String idDetail = idTransaksi + "-" + i;
                String idObat = Tbl_Keranjang.getValueAt(i, 0).toString();
                int jumlah = Integer.parseInt(Tbl_Keranjang.getValueAt(i, 3).toString());
                int subtotal = Integer.parseInt(Tbl_Keranjang.getValueAt(i, 4).toString());
                
                String sqlDetail = "INSERT INTO detail_jual VALUES (?, ?, ?, ?, ?)";
                PreparedStatement pstDetail = conn.prepareStatement(sqlDetail);
                pstDetail.setString(1, idDetail);
                pstDetail.setString(2, idTransaksi);
                pstDetail.setString(3, idObat);
                pstDetail.setInt(4, jumlah);
                pstDetail.setInt(5, subtotal);
                pstDetail.execute();
                
                // Update Stok Obat (-)
                String sqlStok = "UPDATE obat SET stok = stok - ? WHERE id_obat=?";
                PreparedStatement pstStok = conn.prepareStatement(sqlStok);
                pstStok.setInt(1, jumlah);
                pstStok.setString(2, idObat);
                pstStok.execute();
            }
            
            JOptionPane.showMessageDialog(null, "Pembayaran Berhasil! Terima kasih sudah berbelanja.");
            
            // Reset
            tabMode.setRowCount(0);
            totalBelanja = 0;
            Lbl_Total.setText("Total Belanja: Rp 0");
            loadObat(); // Refresh agar obat yg habis hilang dari pilihan
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Checkout: " + e.getMessage());
        }
    }//GEN-LAST:event_Btn_BayarActionPerformed

    private void Btn_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LogoutActionPerformed
        UserSession.logout();
        new Form_Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Form_TokoPelanggan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Bayar;
    private javax.swing.JButton Btn_Logout;
    private javax.swing.JButton Btn_Tambah;
    private javax.swing.JComboBox<String> Cb_Obat;
    private javax.swing.JTextField Ed_Jumlah;
    private javax.swing.JTextField Ed_Subtotal;
    private javax.swing.JLabel Lbl_Total;
    private javax.swing.JLabel Lbl_Welcome;
    private javax.swing.JTable Tbl_Keranjang;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
